export const LOGIN_START='LOGIN_START'
export const LOGIN_FAILURE='LOGIN_FAILURE';
export const LOGIN_SUCCESS='LOGIN_SUCCESS';

export const SIGNUP_START='SIGNUP_START'
export const SIGNUP_FAILURE='SIGNUP_FAILURE';
export const SIGNUP_SUCCESS='SIGNUP_SUCCESS';

export const AUTHENTICATE_USER_START='AUTHENTICATE_USER_START';
export const AUTHENTICATE_USER_SUCCESS='AUTHENTICATE_USER_SUCCESS';
export const AUTHENTICATE_USER_FAILURE='AUTHENTICATE_USER_FAILURE';

export const SELECT_APPLIANCES_START='SELECT_APPLIANCES_START';
export const SELECT_APPLIANCES_SUCCESS='SELECT_APPLIANCES_SUCCESS';
export const SELECT_APPLIANCES_FAILURE='SELECT_APPLIANCES_FAILURE';

export const REFRESH_APPLIANCES_START = 'REFRESH_APPLIANCES_START';
export const REFRESH_APPLIANCES_FAILURE = 'REFRESH_APPLIANCES_FAILURE';
export const REFRESH_APPLIANCES_SUCCESS = 'REFRESH_APPLIANCES_SUCCESS';