export const LOGIN_START='LOGIN_START'
export const LOGIN_FAILURE='LOGIN_FAILURE';
export const LOGIN_SUCCESS='LOGIN_SUCCESS';

export const SIGNUP_START='SIGNUP_START'
export const SIGNUP_FAILURE='SIGNUP_FAILURE';
export const SIGNUP_SUCCESS='SIGNUP_SUCCESS';